### ISSUE TITLE
파이어베이스 인증이 간헐적으로 풀립니다

### ISSUE THREAD

**Issue by ChangJoo-Park** [zerobased-co/veryslide#2]
가끔 새로고침 할 때 권한이 없다고 나옵니다
콘솔에 나오는 에러 첨부합니다 

```
Error retrieving document: FirebaseError: Missing or insufficient permissions.
    at new t (https://veryslide.com/bundle.js:831:524)
    at e.fromRpcStatus (https://veryslide.com/bundle.js:1220:455)
    at e.fromWatchChange (https://veryslide.com/bundle.js:1220:8850)
    at t.onMessage (https://veryslide.com/bundle.js:1122:5848)
    at https://veryslide.com/bundle.js:1122:4591
    at https://veryslide.com/bundle.js:1122:5409
    at https://veryslide.com/bundle.js:896:8994
```

트위터에서 개발과정 잘보고있습니다 👍

**Comment by lqez** [comment]
Thank you for using Veryslide.
I'd failed to reproduce this issue, could you describe more about the environment and situation?
